version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: django_webapp
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_app
    stdin_open: true

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_setup.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume: