# Generated by Django 5.1 on 2025-02-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
