# Generated by Django 5.1 on 2025-02-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_order',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_order',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
