# Generated by Django 5.1 on 2025-02-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_name_order_order_phone_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_order',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
