# Generated by Django 5.1 on 2025-03-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor',
            new_name='user',
        ),
    ]
